site_name: QGIS Command Bar
pages:
- ['index.md', 'About', 'Home']
- ['api.md', 'API', 'API']
- ['usercommands.md', 'API', 'Adding user commands']
- ['plugin_commands.md', 'API', 'Adding Commands from a plugin']
theme: readthedocs
